# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\"e\n\x07Payload\x12\x17\n\x05\x61lert\x18\x01 \x01(\x0b\x32\x06.AlertH\x00\x12\x1b\n\x07message\x18\x02 \x01(\x0b\x32\x08.MessageH\x00\x12\x19\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x07.ActionH\x00\x42\t\n\x07payload\"X\n\x05\x41lert\x12\x19\n\x04type\x18\x01 \x02(\x0e\x32\x0b.Alert.Name\"4\n\x04Name\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0f\x42\x41\x44_CREDENTIALS\x10\x01\x12\r\n\tCONNECTED\x10\x02\"\x91\x01\n\x0cMediaMessage\x12\x0f\n\x07\x63\x61ption\x18\x01 \x02(\t\x12\x0b\n\x03url\x18\x02 \x02(\t\x12 \n\x04type\x18\x03 \x02(\x0e\x32\x12.MediaMessage.Type\"A\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\t\n\x05VIDEO\x10\x02\x12\x0b\n\x07STICKER\x10\x03\x12\x0c\n\x08\x44OCUMENT\x10\x04\"\x1b\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x02(\t\"}\n\x07Message\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07\x66rom_me\x18\x02 \x01(\x08\x12%\n\x0cmediaMessage\x18\x03 \x01(\x0b\x32\r.MediaMessageH\x00\x12#\n\x0btextMessage\x18\x04 \x01(\x0b\x32\x0c.TextMessageH\x00\x42\t\n\x07message\"\xc9\x01\n\x06\x41\x63tion\x12\x1a\n\x04name\x18\x01 \x02(\x0e\x32\x0c.Action.Name\x12\x0f\n\x07\x66rom_me\x18\x02 \x01(\x08\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\"y\n\x04Name\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04PAIR\x10\x01\x12\n\n\x06PAIRED\x10\x02\x12\n\n\x06\x43LOSED\x10\x03\x12\x11\n\rWS_DISCONNECT\x10\x04\x12\x0b\n\x07\x43ONNECT\x10\x05\x12\x0b\n\x07TIMEOUT\x10\x06\x12\r\n\tDUPLICATE\x10\x07\x12\t\n\x05\x43LOSE\x10\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYLOAD._serialized_start=17
  _PAYLOAD._serialized_end=118
  _ALERT._serialized_start=120
  _ALERT._serialized_end=208
  _ALERT_NAME._serialized_start=156
  _ALERT_NAME._serialized_end=208
  _MEDIAMESSAGE._serialized_start=211
  _MEDIAMESSAGE._serialized_end=356
  _MEDIAMESSAGE_TYPE._serialized_start=291
  _MEDIAMESSAGE_TYPE._serialized_end=356
  _TEXTMESSAGE._serialized_start=358
  _TEXTMESSAGE._serialized_end=385
  _MESSAGE._serialized_start=387
  _MESSAGE._serialized_end=512
  _ACTION._serialized_start=515
  _ACTION._serialized_end=716
  _ACTION_NAME._serialized_start=595
  _ACTION_NAME._serialized_end=716
# @@protoc_insertion_point(module_scope)
